version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: search
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_URI: "postgresql://admin:admin@localhost:5432/search"
    ports:
      - "5432:5432"
    # volumes:
    #   - ~/postgres-rl:/var/lib/postgresql/data
    # restarts: always

  streamlit:
    build:
      context: ./app
    volumes:
      - ./app:/app
      - ./database:/app/database

    ports:
      - "8501:8501"
    depends_on:
      - db
